add_requires("spdlog 1.13.x", {system = false})
add_requires("xcb", {system = true})
add_requires("xcb-util", {system = true})
add_requires("xcb-util-image", {system = true})
add_requires("libpng", {system = true})

target("sdl_example")
    set_default(false)
    set_group("example")
    set_kind("binary")
    set_languages("c17", "c++17")
    add_files("./sdl.cpp")
    add_packages("libsdl", "spdlog", "hello-imgui")

target("him_example")
    set_default(false)
    set_group("example")
    set_kind("binary")
    set_languages("c17", "c++17")
    add_files("./imgui.cpp")
    add_includedirs("$(projectdir)/include")
    if is_mode("debug") then
        add_defines("SMV_DEBUG")
    end
    add_packages("spdlog", "hello-imgui")

target("tracking")
    set_default(false)
    set_group("example")
    set_kind("binary")
    set_languages("c17", "c++17")
    add_files("./tracking.cpp")
    add_includedirs("$(projectdir)/include")
    add_packages("spdlog")

target ("listen")
    set_default(false)
    set_group("example")
    set_kind("binary")
    set_languages("c17", "c++17")
    add_files("./listen.cpp")
    add_includedirs("$(projectdir)/include")

target ("screenshot")
    set_default (false)
    set_group("example")
    set_kind("binary")
    set_languages("c17", "c++17")
    add_files("./x11-screenshot.cpp")
    add_packages("xcb", "xcb-util", "xcb-util-image", "spdlog", "libpng")
    add_includedirs("$(projectdir)/include")
