add_requires("xcb", {system = true})
add_requires("xcb-util", {system = true})
add_requires("xcb-util-wm", {system = true})
add_requires("xcb-util-errors", {system = false})
add_requires("libassert 1.2.2", { alias = "libassert", configs = { decompose = true} })

target("libcapture")
    set_kind("static")
    add_files("./**.cpp")
    add_includedirs("details", "common", "$(projectdir)/include")
    add_packages("spdlog")
    add_packages("xcb", "xcb-util", "xcb-util-wm", "xcb-util-errors", "libassert")
    add_syslinks("pthread")
